INSERT INTO tb_user (name, email, password) VALUES ('Ana', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');
--INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ficção científica');
INSERT INTO tb_genre (name) VALUES ('Animação');
INSERT INTO tb_genre (name) VALUES ('Terror');
INSERT INTO tb_genre (name) VALUES ('Ação');

INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pGZZ2FZtDSAwM80h9iYkrbJGrKz.jpg', '', 'Num futuro próximo, a guerra entre humanos e máquinas foi deflagrada. Com a tecnologia a seu dispor, um plano inusitado é arquitetado pelas máquinas ao enviar para o passado um andróide (Arnold Schwarzenegger) com a missão de matar a mãe (Linda Hamilton) daquele que viria a se transformar num líder e seu pior inimigo. Contudo, os humanos também conseguem enviar um representante (Michael Biehn) para proteger a mulher e tentar garantir o futuro da humanidade.', 'O EXTERMINADOR DO FUTURO', 1984, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3TozsOOvgppyDQPVPQntmJhviRF.jpg', 'O Julgamento Final', 'Uma criança destinada a ser líder (Edward Furlong) já nasceu, mas infeliz por viver com pais adotivos, pois foi privado da companhia da mãe (Linda Hamilton), que foi considerada louca quando falou de um exterminador vindo do futuro. Neste contexto, um andróide (Arnold Schwarzenegger) vem do futuro, mais exatamente um modelo T-800 igual ao filme original, para proteger o garoto, mas existe um problema: o mais avançado andróide existente no futuro, um modelo T-1000 (Robert Patrick), que feito de "metal líquido", não pode ter nenhum dano permanente e pode assumir a forma que desejar, também veio para o passado com a missão de matar o menino.', 'O EXTERMINADOR DO FUTURO 2', 1991, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/dPe8uebc7usAgXzBJ6IvKGHEuaD.jpg', 'O CARRO ASSASSINO', 'Arnie Cunningham (Keith Gordon) adora Christine, um carro modelo 1958 Plymouth Fury que não está em seu melhor estado. Decidido a restaurá-la a qualquer custo, Arnie dedica todo seu tempo para ela, o que faz com que se afaste dos amigos e da própria realidade. Leigh (Alexandra Paul), sua namorada, e Dennis (John Stockwell), seu melhor amigo, procuram o antigo dono de Christine e descobrem que o mesmo aconteceu com ele, antes de vender o carro. É quando eles chegam à conclusão que o único meio de resgatar Arnie é destruindo Christine.', 'CHRISTINE', 1983, 3);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/dPe8uebc7usAgXzBJ6IvKGHEuaD.jpg', '', 'Atingido por um raio, o robô conhecido apenas como "Número 5" escapa de uma empresa de eletrônica experimental. Newton Crosby (Steve Guttenberg) e seu assistente Ben Jabituya (Fisher Stevens) são convocados para tentar localizá-lo. Nº 5 encontra a ecologista Stephanie Speck (Ally Sheedy), esperando ensinar tudo para o "alienígena", ela preenche o banco de memória de Nº 5 com cultura pop e é aí que começa a confusão. Filme também conhecido pelo título, O Incrível Robô.', 'Um Robô em Curto Circuito', 1986, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/k0MK2zSSnV6TqIm8aTjw7yIaOCr.jpg', '', '"Número 5", também chamado "Johnny 5", o incrível e adorável robô em curto circuito, está de volta nesta acelerada comédia de ação que vai deixar a cidade de cabeça para baixo. O curioso Johnny 5 sai para um reconhecimento da cidade, mas alguns vadios de rua, um banqueiro ganancioso e uma gangue de pilantras percebem sua inocência e vêem sua passagem de alta tecnologia para faturar. Será que Johnny 5 vai sobreviver à grande cidade e esses escroques? Fique conectado neste filme de alta voltagem para saber a resposta.', 'Um Robô em Curto Circuito 2', 1988, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7ooQfn194Gz4YwJn3hQj8MPMWBQ.jpg', 'O Policial do Futuro', 'Policial é morto em combate e transformado por cientistas da empresa que dirige a força policial em um ciborgue ultrassofisticado a fim de ser usado na luta contra o crime na cidade de Detroit. Porém, apesar de ter sua memória apagada, lembranças o assombram e o levam a buscar vingança.', 'RoboCop', 1987, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pjLdH5VIKirwVUIZ0iDisXoRGo4.jpg', '', 'Em um distante futuro, um pequeno robô coletor de lixo embarca em uma jornada espacial que acabará por decidir o destino da humanidade.', 'Wall-e', 2008, 2);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/dJrYUXjgYAD95Ho67t7Utdqv8At.jpg', 'Programado Para Matar', 'John Rambo é um veterano de guerra atormentado pelas lembranças do Vietnã. Numa viagem à procura de um colega do exército, passa por uma cidadezinha cujo xerife o toma por vagabundo, e acaba detido. Lá, a agressividade dos policiais traz à tona todos os seus traumas, mas também toda sua habilidade de guerra. Rambo foge, então, para uma floresta vizinha, e dá início a uma caçada explosiva, em que será preciso toda uma força policial para combater um só homem.', 'Rambo', 1982, 4);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/x2UmaR2tUqIzD6aHa0tIxrqYjOc.jpg', '', 'Um grupo de adolescentes tem pesadelos horríveis, onde são atacados por um homem deformado com garras de aço. Ele apenas aparece durante o sono e, para escapar, é preciso acordar. Os crimes vão ocorrendo seguidamente, até que se descobre que o ser misterioso é na verdade Freddy Krueger (Robert Englund), um homem que molestou crianças na rua Elm e que foi queimado vivo pela vizinhança. Agora Krueger pode retornar para se vingar daqueles que o mataram, através do sono.', 'A Hora do Pesadelo', 1984, 3);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aCsggxaOJo9tLrt297Bc5cT3nCY.jpg', 'O Filme', 'Um fenômeno alienígena de poder e tamanho descomunal se aproxima da Terra, destruindo tudo em seu caminho. A única nave que pode enfrentar esta força letal que ameaça a Terra é a U.S.S. Enterprise. O lendário comandante James T. Kirk (William Shatner) é convocado para a missão, mas um perigo não previsto pode destruir a U.S.S. Enterprise e toda a sua tripulação.', 'Jornada nas estrelas', 1980, 1);
INSERT INTO tb_movie (img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rxdSNzq3hofvyakEgKt2zfTN5tJ.jpg', 'Episódio I - A Ameaça Fantasma', 'Enquanto resgatam a Rainha Amidala, governante de um planeta pacífico invadido por forças ameaçadoras, os Cavaleiros Jedi Obi-Wan Kenobi e Qui-Gon Jinn descobrem Anakin Skywalker, uma criança prodígio de 9 anos excepcionalmente poderosa na Força.', 'Star Wars', 1999, 1);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Incrível esse filme, incrível a história de produção deste filme. James Cameron está de parabéns!!', 1, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Esse filme é um verdadeiro clássico, uma obra prima.', 2, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Cara, não canso de ver esse filmeee. "Come with me if you want to live"', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Carro muito lindoo, mas da muito medo', 3, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Alguém sabe onde consigo uma miniatura desse carro?? Plymouth Fury 1958', 3, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('O melhor filme da sessão da tarde, que saudades', 4, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('RoboCop x ED-209, shoow', 6, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Considero esse filme a obra prima da Pixar, robozinho cativante', 7, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Nostalgia em ver esse filme', 8, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Sério, esse filme devia estar na categoria de comédia', 9, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Eu concordo kkkkk', 9, 1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('A série é a melhor que já vi, mesmo tendo todo aquele efeito antigão', 10, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Que a força estaja com você', 11, 1);